# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'worker' do
    
    pod 'AFNetworking', '~>2.3.1'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'MJRefresh','~> 3.1.0'
    pod 'Masonry','~> 1.0.2'
    pod 'SVProgressHUD','~> 2.1.2'
    pod 'BaiduMapKit'
    pod 'JPush', '3.0.2'
    pod 'YYKit'
    pod 'FMDB'
    
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMengUShare/UI'

    # 集成微信(完整版14.4M)
    pod 'UMengUShare/Social/WeChat'
    
    # 集成QQ/QZone/TIM(完整版7.6M)
    pod 'UMengUShare/Social/QQ'
    
    # 集成新浪微博(完整版25.3M)
    pod 'UMengUShare/Social/Sina'


  target 'workerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'workerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
