# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'worker' do
    
    pod 'AFNetworking', '~>2.3.1'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'MJRefresh','~> 3.1.0'
    pod 'Masonry','~> 1.0.2'
    pod 'SVProgressHUD','~> 2.1.2'
   
   

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for worker

  target 'workerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'workerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
